import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Box } from '@mui/material'
import Navbar from './Navbar'
import Provider from './context/Provider'
import QueryClientProvider from './QueryClientProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true} >
      
      
        <body >
        <QueryClientProvider>
          <Provider>
            <Navbar/>
          <main style={{marginTop:'64px'}}>{children}</main>
          </Provider>
          </QueryClientProvider>
          </body>   
    </html>
  )
}
